# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Site settings
title: Stuff and That
email: n@kerk.in
description: > # this means to ignore newlines until "baseurl:"
  A collection of thoughts
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://blog.kerk.in" # the base hostname & protocol for your site
twitter_username: nkerkin
github_username:  nkerkin

author:
  name: 'Neil Kerkin'
  url:  https://twitter.com/nkerkin

paginate:         5

# Custom vars
version:  1.0.0

# github:
#   repo: nkerkin/nkerkin.github.io

repository: nkerkin/nkerkin.github.io

encoding: utf-8